# Generated by Django 5.1.15 on 2026-09-14 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('gift_finder_started', 'Gift Finder Started'), ('gift_finder_completed', 'Gift Finder Completed'), ('recommendation_shown', 'Recommendation Shown'), ('recommendation_clicked', 'Recommendation Clicked'), ('product_viewed', 'Product Viewed'), ('wishlist_added', 'Wishlist Added'), ('cart_added', 'Cart Added'), ('checkout_started', 'Checkout Started'), ('order_placed', 'Order Placed'), ('payment_success', 'Payment Success'), ('review_submitted', 'Review Submitted')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomora_analytics',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='bloomora_an_event_t_fca5c9_idx')],
            },
        ),
    ]
