"""
Bloomora Seed Command
Seeds the database with categories, occasions, sellers, and comprehensive products spanning all gift types.
Usage: python manage.py seed_bloomora
"""
from django.core.management.base import BaseCommand
from django.db import transaction


CATEGORIES = [
    {"name": "Floral Arrangements", "slug": "flowers", "icon": "Flower2", "description": "Hand-arranged fresh blooms & luxury bouquets", "sort_order": 1},
    {"name": "Velvet Box Bouquets", "slug": "bouquets", "icon": "Gift", "description": "Handcrafted floral art in signature velvet cylindrical hatboxes", "sort_order": 2},
    {"name": "Gourmet Bento Cakes", "slug": "cakes", "icon": "Cake", "description": "Artisanal single-portion chocolate truffle mini cakes & celebratory sweets", "sort_order": 3},
    {"name": "Chocolate Bouquets", "slug": "chocolate-bouquets", "icon": "Sparkles", "description": "Ferrero Rocher & Swiss truffles paired with satin roses in keepsake boxes", "sort_order": 4},
    {"name": "Personalized Keepsakes", "slug": "personalized", "icon": "Heart", "description": "Illuminated photo memory frames, engraved star maps & custom plaques", "sort_order": 5},
    {"name": "Custom Keepsakes & Mugs", "slug": "custom-gifts", "icon": "Coffee", "description": "Handcrafted ceramic mugs and personalized memory keepsakes", "sort_order": 6},
    {"name": "Jewellery & Accessories", "slug": "jewellery", "icon": "Crown", "description": "Sterling silver pendants, charm bracelets and fine handcrafted accessories", "sort_order": 7},
    {"name": "Luxury Fragrances & Candles", "slug": "fragrances-candles", "icon": "Flame", "description": "Scented soy candles, aromatherapy sets and botanical wax tablets", "sort_order": 8},
    {"name": "Beauty & Self-Care Spa Kits", "slug": "beauty-wellness", "icon": "Heart", "description": "Organic rosewater, lavender bath rituals and pampering self-care hampers", "sort_order": 9},
    {"name": "Plants & Eco Living", "slug": "plants", "icon": "Leaf", "description": "Bonsai trees, lucky bamboo and air-purifying indoor succulents in ceramic planters", "sort_order": 10},
    {"name": "Books, Stationery & Journals", "slug": "books-stationery", "icon": "BookOpen", "description": "Debossed vegan leather journals, calligraphy sets & executive brass pens", "sort_order": 11},
    {"name": "Corporate & Executive Gifts", "slug": "corporate-gifts", "icon": "Briefcase", "description": "Luxury branded diaries, precision pens, onboarding suites & boardroom sets", "sort_order": 12},
    {"name": "Kids Art, Crafts & DIY", "slug": "kids-gifting", "icon": "Palette", "description": "Age-tiered creative hampers fostering tactile exploration, painting & STEM", "sort_order": 13},
    {"name": "Baby & New Parent Hampers", "slug": "baby-gifts", "icon": "Smile", "description": "Organic cotton swaddles, milestone journals & keepsake hampers", "sort_order": 14},
    {"name": "Royal Reserve Hampers", "slug": "premium-gifts", "icon": "Crown", "description": "Handcrafted wooden chests, gourmet nuts & Belgian truffles", "sort_order": 15},
    {"name": "Gourmet & Dry Fruit Hampers", "slug": "gourmet-hampers", "icon": "ShoppingBag", "description": "Roasted artisanal dry fruits, honey spreads and festive gourmet trays", "sort_order": 16},
    {"name": "Pocket Surprises & Gestures", "slug": "mini-gifts", "icon": "Gift", "description": "Charming sweet gestures and budget-friendly tokens under Rs.299", "sort_order": 17},
]

OCCASIONS = [
    {"name": "Birthday Celebration", "slug": "birthday", "emoji": "🎉"},
    {"name": "Love & Romance", "slug": "love", "emoji": "❤️"},
    {"name": "Anniversary Milestone", "slug": "anniversary", "emoji": "🥂"},
    {"name": "Proposal Moment", "slug": "proposal", "emoji": "💍"},
    {"name": "Congratulations", "slug": "congratulations", "emoji": "🌟"},
    {"name": "Gratitude & Care", "slug": "thank-you", "emoji": "🙏"},
    {"name": "Wedding Gift", "slug": "wedding", "emoji": "👰"},
    {"name": "Graduation Gift", "slug": "graduation", "emoji": "🎓"},
    {"name": "Friendship Day", "slug": "friendship", "emoji": "🤝"},
    {"name": "Apology Gift", "slug": "sorry", "emoji": "🌸"},
    {"name": "Mother's Day", "slug": "mothers-day", "emoji": "💐"},
    {"name": "Father's Day", "slug": "fathers-day", "emoji": "👔"},
    {"name": "Housewarming", "slug": "housewarming", "emoji": "🏡"},
    {"name": "New Baby Arrival", "slug": "new-baby", "emoji": "👶"},
    {"name": "Festivals & Diwali", "slug": "festivals", "emoji": "🎆"},
    {"name": "Just Because", "slug": "just-because", "emoji": "✨"},
]

PRODUCTS_DATA = [
    # ── 1. FLOWERS ──
    {
        "name": "A Beautiful Birthday Surprise",
        "subtitle": "2 Dutch Red Roses + Dairy Milk Silk + Gold Ribbon",
        "description": "Two long-stem Dutch red roses paired with Cadbury Dairy Milk Silk (60g), wrapped in soft ivory matte paper with signature gold velvet ribbon and custom gold foil greeting card.",
        "story": "Designed to transform a modest budget into a moment of pure unboxing joy.",
        "price": 249,
        "original_price": 349,
        "category_slug": "flowers",
        "stock": 50,
        "images": ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80"],
        "tags": ["roses", "chocolate", "birthday", "love", "budget-friendly", "flowers"],
        "occasions": ["birthday", "love", "proposal", "anniversary"],
        "emotions": ["loved", "appreciated", "surprised"],
        "recipient_types": ["for-her", "partner", "girlfriend", "wife"],
        "interests": ["flowers", "chocolate"],
        "budget_tier": "200-299",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Optimal visual balance of flowers & chocolates within Rs.250 budget.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "12 Red Roses Luxe Botanical Bouquet",
        "subtitle": "12 Long-Stem Dutch Scarlet Roses in Signature Paper",
        "description": "Twelve velvety long-stem red roses hand-tied with white gypsophila and eucalyptus sprigs, wrapped in waterproof blush tissue with a gold ribbon seal.",
        "story": "A classic proclamation of admiration and heartfelt devotion.",
        "price": 899,
        "original_price": 1199,
        "category_slug": "flowers",
        "stock": 40,
        "images": ["https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=80"],
        "tags": ["roses", "luxury", "red roses", "anniversary", "proposal", "flowers"],
        "occasions": ["anniversary", "love", "proposal", "birthday", "wedding"],
        "emotions": ["loved", "cherished", "surprised"],
        "recipient_types": ["for-her", "partner", "wife", "girlfriend"],
        "interests": ["flowers", "romance"],
        "budget_tier": "500-999",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "High-impact romantic bouquet for milestones and anniversaries.",
        "location": "Rajahmundry, Surampalem",
    },
    {
        "name": "Pastel Whispers Mixed Orchids & Carnations",
        "subtitle": "Purple Dendrobium Orchids & Soft Pink Carnations",
        "description": "Exotic Thai purple dendrobium orchids paired with pastel pink carnations and green fillers in dual-tone Korean wrapping.",
        "story": "Graceful and dignified, perfect for expressing admiration and deep gratitude.",
        "price": 649,
        "original_price": 849,
        "category_slug": "flowers",
        "stock": 30,
        "images": ["https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80"],
        "tags": ["orchids", "carnations", "pastel", "gratitude", "flowers"],
        "occasions": ["thank-you", "mothers-day", "congratulations", "birthday"],
        "emotions": ["appreciated", "cherished", "loved"],
        "recipient_types": ["for-parents", "mother", "mom", "teacher", "colleague"],
        "interests": ["flowers", "art"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 20,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Sophisticated floral composition ideal for mothers and mentors.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 2. VELVET BOUQUETS ──
    {
        "name": "Signature Velvet Box Rose Arrangement",
        "subtitle": "Handcrafted Premium Roses in Matte Cylindrical Velvet Hatbox",
        "description": "A breathtaking cylindrical velvet box filled with hand-selected long-stem roses, delicate baby's breath, and bespoke greenery with built-in hydration core.",
        "story": "Crafted for high-emotion milestones. The deep tactile velvet exterior transforms an ordinary bouquet into a regal luxury keepsake.",
        "price": 1499,
        "original_price": 1999,
        "category_slug": "bouquets",
        "stock": 20,
        "images": ["https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80"],
        "tags": ["velvet", "hatbox", "luxury", "anniversary", "preserved", "bouquets"],
        "occasions": ["anniversary", "proposal", "birthday", "love", "wedding"],
        "emotions": ["loved", "cherished", "celebrated"],
        "recipient_types": ["for-her", "partner", "wife", "girlfriend"],
        "interests": ["flowers", "luxury", "home-decor"],
        "budget_tier": "1000-plus",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 4,
        "preparation_time_minutes": 30,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Award-winning cylindrical velvet presentation for landmark celebrations.",
        "location": "Rajahmundry, Vijayawada, Surampalem",
    },

    # ── 3. GOURMET BENTO CAKES ──
    {
        "name": "Bento Belgian Dark Chocolate Truffle Cake",
        "subtitle": "Artisanal Single-Portion Ganache Cake in Eco Sugar-Cane Box",
        "description": "A rich 350g Belgian 54% dark chocolate truffle bento cake layered with silky whipped ganache, topped with gold leaf flakes and a mini candle.",
        "story": "Freshly baked on order by local partner patisseries. Perfect for intimate sweet celebrations.",
        "price": 349,
        "original_price": 449,
        "category_slug": "cakes",
        "stock": 35,
        "images": ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80"],
        "tags": ["bento cake", "chocolate", "truffle", "cake", "birthday", "sweet"],
        "occasions": ["birthday", "anniversary", "congratulations", "friendship"],
        "emotions": ["celebrated", "loved", "surprised"],
        "recipient_types": ["for-friends", "for-her", "for-him", "sibling", "partner"],
        "interests": ["chocolate", "food"],
        "budget_tier": "300-499",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 25,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Top trending single-portion celebratory cake for sweet moments.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "Red Velvet & Berry Cream Bento Cake",
        "subtitle": "Velvety Sponge with Cream Cheese Frosting & Fresh Berries",
        "description": "Crimson red velvet sponge layered with smooth Philadelphia-style cream cheese frosting and blueberry compote in an ivory bento box with satin tie.",
        "story": "Created for romantic and milestone celebrations where sweetness speaks loudest.",
        "price": 399,
        "original_price": 499,
        "category_slug": "cakes",
        "stock": 30,
        "images": ["https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80"],
        "tags": ["red velvet", "cake", "bento", "romantic", "berries", "dessert"],
        "occasions": ["love", "anniversary", "birthday", "proposal"],
        "emotions": ["loved", "surprised", "celebrated"],
        "recipient_types": ["for-her", "partner", "wife", "girlfriend"],
        "interests": ["food", "chocolate"],
        "budget_tier": "300-499",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 25,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Romantic culinary centerpiece ideal for partner birthdays and dates.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 4. CHOCOLATE BOUQUETS ──
    {
        "name": "The Golden Truffle & Satin Treasure",
        "subtitle": "16 Golden Ferrero Truffles in Cylinder Box",
        "description": "16 golden Ferrero Rocher pralines intricately woven with artificial cream satin roses in a rigid midnight black and gold foil cylinder box.",
        "story": "Created for grand milestones. Loved for anniversaries and celebrations where elegance meets indulgence.",
        "price": 899,
        "original_price": 1199,
        "category_slug": "chocolate-bouquets",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80"],
        "tags": ["ferrero", "luxury", "satin", "anniversary", "premium", "chocolate"],
        "occasions": ["anniversary", "birthday", "wedding", "congratulations"],
        "emotions": ["loved", "celebrated", "appreciated"],
        "recipient_types": ["for-her", "for-him", "partner", "friend"],
        "interests": ["chocolate", "luxury"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Highest luxury rating for milestone anniversaries & grand celebrations.",
        "location": "Rajahmundry, Surampalem",
    },
    {
        "name": "Sweet Moments Pocket Chocolate Bouquet",
        "subtitle": "Cadbury Silk + 4 Dairy Milk Bars with Soft Blush Wrapping",
        "description": "A delightful handheld chocolate bouquet featuring Cadbury Dairy Milk Silk and 4 Dairy Milk bars wrapped in artistic blush crepe with satin bow.",
        "story": "Budget-friendly sweet indulgence designed to make someone grin instantly.",
        "price": 279,
        "original_price": 349,
        "category_slug": "chocolate-bouquets",
        "stock": 45,
        "images": ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80"],
        "tags": ["chocolate", "bouquet", "cadbury", "silk", "pocket-friendly"],
        "occasions": ["birthday", "thank-you", "friendship", "sorry"],
        "emotions": ["appreciated", "surprised", "loved"],
        "recipient_types": ["for-friends", "sibling", "friend", "colleague"],
        "interests": ["chocolate"],
        "budget_tier": "200-299",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 1,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Delicious chocolate bouquet under Rs.300 for students and friends.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },

    # ── 5. PERSONALIZED KEEPSAKES ──
    {
        "name": "Illuminated Acrylic Memory Frame Set",
        "subtitle": "LED Photo Acrylic Frame + Warm Floral Accent",
        "description": "An LED illuminated clear acrylic frame customized with your favorite high-res photo & custom message, with warm wooden USB glow base.",
        "story": "Turn a cherished photograph into an illuminated nighttime masterpiece.",
        "price": 799,
        "original_price": 999,
        "category_slug": "personalized",
        "stock": 20,
        "images": ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80"],
        "tags": ["photo", "personalized", "LED", "acrylic", "memory", "frame"],
        "occasions": ["anniversary", "birthday", "love", "graduation", "wedding"],
        "emotions": ["cherished", "remembered", "loved"],
        "recipient_types": ["for-him", "for-her", "partner", "parents", "mother", "father"],
        "interests": ["photography", "technology", "art"],
        "budget_tier": "500-999",
        "customizable": True,
        "supports_photo_customization": True,
        "supports_text_customization": True,
        "same_day_available": False,
        "delivery_time_hours": 24,
        "preparation_time_minutes": 30,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Custom photo LED illumination for personalized memory preservation.",
        "location": "Rajahmundry, Vijayawada",
    },
    {
        "name": "Customized Engraved Wooden Memory Plaque",
        "subtitle": "Solid Beech Wood with Laser Engraved Photo & Dedication",
        "description": "Natural grain steamed beech wood plaque engraved with your photo and custom text, protected with a natural beeswax coat and desktop easel stand.",
        "story": "An heirloom-grade physical keepsake that will stay on their desk for decades.",
        "price": 599,
        "original_price": 799,
        "category_slug": "personalized",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80"],
        "tags": ["wood", "engraved", "personalized", "plaque", "anniversary", "keepsake"],
        "occasions": ["anniversary", "mothers-day", "fathers-day", "thank-you", "wedding"],
        "emotions": ["remembered", "cherished", "appreciated"],
        "recipient_types": ["for-parents", "mother", "father", "partner", "mentor"],
        "interests": ["art", "home-decor", "photography"],
        "budget_tier": "500-999",
        "customizable": True,
        "supports_photo_customization": True,
        "supports_text_customization": True,
        "same_day_available": False,
        "delivery_time_hours": 24,
        "preparation_time_minutes": 30,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Timeless laser engraved natural wood plaque.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 6. CUSTOM GIFTS & CERAMIC MUGS ──
    {
        "name": "Artisanal Hand-Glazed Ceramic Keepsake Mug",
        "subtitle": "High-Fired 350ml Stoneware Mug with Custom Name Initial",
        "description": "Hand-thrown ceramic stoneware mug with a tactile speckled cream glaze, comfortable ergonomic thumb-rest, and hand-painted golden monogram.",
        "story": "Elevates every morning coffee or chai into a mindful ritual.",
        "price": 349,
        "original_price": 499,
        "category_slug": "custom-gifts",
        "stock": 40,
        "images": ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
        "tags": ["mug", "ceramic", "coffee", "tea", "custom", "handcrafted"],
        "occasions": ["birthday", "thank-you", "friendship", "congratulations"],
        "emotions": ["appreciated", "remembered", "loved"],
        "recipient_types": ["for-friends", "for-colleagues", "colleague", "teacher", "sibling", "partner"],
        "interests": ["coffee", "art", "books"],
        "budget_tier": "300-499",
        "customizable": True,
        "supports_text_customization": True,
        "same_day_available": True,
        "delivery_time_hours": 4,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Warm artisanal morning companion with custom initial debossing.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "Sweet Celebration Gift Tray",
        "subtitle": "3 Roses + Cadbury Celebrations + Golden Sparkler",
        "description": "Three vibrant Dutch roses, Cadbury Celebrations pack, a luxury birthday greeting card, and a golden party sparkler.",
        "story": "Everything needed to light up someone's birthday celebration instantly.",
        "price": 449,
        "original_price": 599,
        "category_slug": "custom-gifts",
        "stock": 35,
        "images": ["https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80"],
        "tags": ["birthday", "celebration", "roses", "sparkler", "tray", "party"],
        "occasions": ["birthday", "congratulations", "friendship"],
        "emotions": ["celebrated", "surprised", "loved"],
        "recipient_types": ["for-friends", "sibling", "friend", "colleague"],
        "interests": ["chocolate", "flowers"],
        "budget_tier": "300-499",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Top rated birthday celebration combo with golden party sparkler.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },

    # ── 7. FINE JEWELLERY & ACCESSORIES ──
    {
        "name": "Sterling Silver 925 Sparkling Heart Pendant",
        "subtitle": "Pure 925 Silver with Swiss Zirconia & Anti-Tarnish Coating",
        "description": "An exquisite heart pendant crafted in certified 925 sterling silver with sparkling Swiss cubic zirconia stones and adjustable 18-inch silver cable chain in a velvet jewel box.",
        "story": "Designed as a dazzling token of lifelong love that shines in every light.",
        "price": 1299,
        "original_price": 1799,
        "category_slug": "jewellery",
        "stock": 20,
        "images": ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80"],
        "tags": ["jewellery", "silver", "pendant", "heart", "necklace", "romantic"],
        "occasions": ["anniversary", "birthday", "love", "proposal", "wedding"],
        "emotions": ["loved", "cherished", "celebrated"],
        "recipient_types": ["for-her", "partner", "wife", "girlfriend"],
        "interests": ["luxury", "art"],
        "budget_tier": "1000-plus",
        "customizable": False,
        "same_day_available": False,
        "delivery_time_hours": 24,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Certified 925 sterling silver heirloom jewellery in signature velvet box.",
        "location": "Rajahmundry, Vijayawada",
    },
    {
        "name": "Minimalist Rose Gold Infinity Charm Bracelet",
        "subtitle": "Dainty Rose Gold Plated Bracelet with Zircon Accents",
        "description": "A delicate infinity charm bracelet in 18K rose gold vermeil on surgical stainless steel with lobster claw clasp and velvet presentation card.",
        "story": "Signifies infinite bonds of love, friendship, or sisterhood.",
        "price": 899,
        "original_price": 1199,
        "category_slug": "jewellery",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1611591475834-0803c621ff46?auto=format&fit=crop&w=800&q=80"],
        "tags": ["jewellery", "bracelet", "infinity", "rose gold", "charm"],
        "occasions": ["birthday", "anniversary", "friendship", "love"],
        "emotions": ["loved", "appreciated", "cherished"],
        "recipient_types": ["for-her", "partner", "girlfriend", "sister", "friend"],
        "interests": ["luxury", "art"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 15,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Modern minimalist infinity bracelet with enduring rose gold shine.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 8. LUXURY FRAGRANCES & SCENTED CANDLES ──
    {
        "name": "French Vanilla & Amber Scented Soy Candle",
        "subtitle": "Hand-Poured 220g 100% Natural Soy Candle in Matte Glass Jar",
        "description": "A luxury aromatherapeutic soy wax candle infused with pure Madagascar vanilla beans, warm golden amber, and a lead-free cotton wick. Burns clean for 45+ hours.",
        "story": "Infuses any bedroom, study, or living space with comforting warmth and serenity.",
        "price": 449,
        "original_price": 599,
        "category_slug": "fragrances-candles",
        "stock": 35,
        "images": ["https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80"],
        "tags": ["candle", "soy candle", "vanilla", "aromatherapy", "home-decor", "fragrance"],
        "occasions": ["birthday", "thank-you", "housewarming", "anniversary", "mothers-day"],
        "emotions": ["cherished", "appreciated", "loved"],
        "recipient_types": ["for-her", "for-parents", "mother", "partner", "friend"],
        "interests": ["home-decor", "coffee", "art"],
        "budget_tier": "300-499",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Clean-burning pure soy wax candle with French vanilla aromatherapy.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "Oud Wood & Lavender Aromatherapy Trio",
        "subtitle": "3 Mini Scented Soy Votives in Rigid Gift Box",
        "description": "A curated olfactory flight of three 80g soy candles: Royal Oud & Bergamot, French Lavender Meadow, and Smoked Sandalwood.",
        "story": "Curated for mindful relaxation, evening reading, and calm retreats.",
        "price": 799,
        "original_price": 999,
        "category_slug": "fragrances-candles",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80"],
        "tags": ["candles", "aromatherapy", "oud", "lavender", "spa", "fragrance"],
        "occasions": ["housewarming", "birthday", "thank-you", "festivals"],
        "emotions": ["cherished", "appreciated", "remembered"],
        "recipient_types": ["for-parents", "mother", "father", "colleague", "partner"],
        "interests": ["home-decor", "books"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 15,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Opulent aromatherapy flight of three artisanal fragrances.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 9. BEAUTY & SELF-CARE SPA KITS ──
    {
        "name": "Rosewater & French Lavender Spa Ritual",
        "subtitle": "Organic Bath Salts + Handcrafted Cold-Pressed Soap + Body Butter",
        "description": "An organic relaxation hamper including Dead Sea lavender bath salts, hand-whipped raw shea body butter, and a natural loofah in a wooden presentation crate.",
        "story": "Transforms an ordinary evening into an indulgent spa sanctuary.",
        "price": 849,
        "original_price": 1099,
        "category_slug": "beauty-wellness",
        "stock": 20,
        "images": ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80"],
        "tags": ["spa", "self-care", "wellness", "rosewater", "lavender", "bath"],
        "occasions": ["birthday", "mothers-day", "thank-you", "anniversary"],
        "emotions": ["cherished", "loved", "appreciated"],
        "recipient_types": ["for-her", "for-parents", "mother", "partner", "wife", "sister"],
        "interests": ["fitness", "home-decor"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 4,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Holistic botanical self-care ritual for stress relief and pampering.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 10. PLANTS & ECO LIVING ──
    {
        "name": "Good Luck Jade Succulent in Artisanal Ceramic Pot",
        "subtitle": "Healthy Live Jade Crassula Plant in Matte White Pot",
        "description": "An auspicious live Jade plant (symbolizing growth and prosperity) potted in premium nutrient-rich organic soil with decorative white river pebbles.",
        "story": "Low maintenance, high oxygen, and a living token of fond memories.",
        "price": 299,
        "original_price": 399,
        "category_slug": "plants",
        "stock": 40,
        "images": ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80"],
        "tags": ["plant", "succulent", "jade", "indoor plant", "green", "eco"],
        "occasions": ["housewarming", "congratulations", "birthday", "thank-you"],
        "emotions": ["appreciated", "remembered", "cherished"],
        "recipient_types": ["for-friends", "for-colleagues", "colleague", "teacher", "neighbour", "father"],
        "interests": ["home-decor", "fitness"],
        "budget_tier": "200-299",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Live prosperity plant requiring minimal care, ideal for desktops.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "Ficus Bonsai Tree in Glazed Terracotta Planter",
        "subtitle": "4-Year Matured S-Shaped Ficus Ginseng with Care Handbook",
        "description": "A matured miniature indoor bonsai with aerial roots in an antique glazed terracotta pot, complete with precision pruning shears and plant food.",
        "story": "A zen living sculpture that grows more beautiful each passing year.",
        "price": 899,
        "original_price": 1299,
        "category_slug": "plants",
        "stock": 20,
        "images": ["https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=800&q=80"],
        "tags": ["bonsai", "plant", "zen", "ficus", "indoor tree", "eco"],
        "occasions": ["fathers-day", "housewarming", "congratulations", "anniversary"],
        "emotions": ["cherished", "remembered", "appreciated"],
        "recipient_types": ["for-parents", "father", "dad", "mentor", "colleague"],
        "interests": ["home-decor", "art"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 4,
        "preparation_time_minutes": 25,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Matured indoor bonsai tree representing patience, wisdom, and longevity.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 11. BOOKS, STATIONERY & LEATHER JOURNALS ──
    {
        "name": "Executive Vegan Leather Diary & Brass Pen Set",
        "subtitle": "Debossed 200-Page Undated Journal with Heavy Matte Brass Pen",
        "description": "Rich saddle-brown vegan leather notebook with magnetic wrap closure, ribbon bookmark, 100gsm acid-free ivory pages, and heavy brass ballpoint pen.",
        "story": "Designed for thinkers, dreamers, and leaders who put ideas on paper.",
        "price": 499,
        "original_price": 699,
        "category_slug": "books-stationery",
        "stock": 35,
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
        "tags": ["diary", "journal", "pen", "stationery", "leather", "executive"],
        "occasions": ["graduation", "congratulations", "birthday", "thank-you"],
        "emotions": ["appreciated", "remembered", "celebrated"],
        "recipient_types": ["for-colleagues", "for-him", "colleague", "teacher", "mentor", "father", "friend"],
        "interests": ["books", "technology"],
        "budget_tier": "300-499",
        "customizable": True,
        "supports_text_customization": True,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Distinguished tactile leather journal and brass pen suite.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },

    # ── 12. CORPORATE & EXECUTIVE ──
    {
        "name": "Executive Desk Trio: Ceramic Mug, Diary & Pen",
        "subtitle": "Curated Workplace Power Set in Rigid Midnight Presentation Box",
        "description": "A refined workplace ensemble featuring a debossed vegan leather executive planner, high-fired matte stoneware mug, and precision metal twist pen.",
        "story": "Elevates daily desk productivity with executive distinction.",
        "price": 749,
        "original_price": 999,
        "category_slug": "corporate-gifts",
        "stock": 30,
        "images": ["https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80"],
        "tags": ["corporate", "executive", "desk set", "mug", "diary", "office"],
        "occasions": ["congratulations", "thank-you", "graduation", "birthday"],
        "emotions": ["appreciated", "celebrated", "remembered"],
        "recipient_types": ["for-colleagues", "for-him", "colleague", "boss", "mentor", "teacher"],
        "interests": ["books", "coffee", "technology"],
        "budget_tier": "500-999",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Complete desk synergy kit for office promotions and corporate gifting.",
        "location": "Rajahmundry, Vijayawada, Surampalem",
    },
    {
        "name": "Boardroom Executive Portfolio & Precision Pen Suite",
        "subtitle": "A4 Bonded Leather Folder with Pad, Powerbank & Metal Pen",
        "description": "A luxury A4 executive portfolio featuring card slots, document pockets, replaceable memo pad, built-in 5000mAh slim powerbank, and dual-tone fountain pen.",
        "story": "Command confidence in every business presentation or boardroom meet.",
        "price": 1599,
        "original_price": 2199,
        "category_slug": "corporate-gifts",
        "stock": 15,
        "images": ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"],
        "tags": ["corporate", "portfolio", "executive", "boardroom", "luxury"],
        "occasions": ["congratulations", "promotion", "graduation"],
        "emotions": ["celebrated", "appreciated"],
        "recipient_types": ["for-colleagues", "colleague", "boss", "mentor", "father"],
        "interests": ["technology", "books"],
        "budget_tier": "1000-plus",
        "customizable": True,
        "same_day_available": False,
        "delivery_time_hours": 24,
        "preparation_time_minutes": 25,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "High-tier corporate executive portfolio for senior partners and directors.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 13. KIDS ART, CRAFTS & TOYS ──
    {
        "name": "Junior Creator Craft Kit with Clay & Paint (Ages 5–7)",
        "subtitle": "Non-Toxic Clay, Watercolor Palette, Brushes & DIY Wooden Frame",
        "description": "An inspiring creative hamper packed with 12 organic modeling clay bars, 18-color watercolor set, 3 natural bristle brushes, DIY wooden photo frame to decorate, and fun sticker pack.",
        "story": "Fosters tactile curiosity, color exploration, and boundless childhood imagination.",
        "price": 749,
        "original_price": 999,
        "category_slug": "kids-gifting",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80"],
        "tags": ["kids", "craft", "art", "paint", "clay", "diy", "toys"],
        "occasions": ["birthday", "congratulations", "festivals"],
        "emotions": ["surprised", "celebrated", "loved"],
        "recipient_types": ["child", "kids", "sibling"],
        "interests": ["art"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 2,
        "preparation_time_minutes": 15,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Pedagogically vetted creative activity kit for developing minds.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },

    # ── 14. BABY & NEW PARENT HAMPERS ──
    {
        "name": "Pure Blossom Organic Cotton Swaddle & Teether Set",
        "subtitle": "2 GOTS-Certified Muslin Swaddles + Natural Beechwood Rattle",
        "description": "Two ultra-breathable pre-washed organic muslin swaddles in subtle pastel animal prints paired with a smooth non-toxic beechwood teething ring.",
        "story": "Gentle on newborn skin, bringing pure comfort to new parents and infants.",
        "price": 699,
        "original_price": 899,
        "category_slug": "baby-gifts",
        "stock": 25,
        "images": ["https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=800&q=80"],
        "tags": ["baby", "swaddle", "organic", "infant", "teether", "new-baby"],
        "occasions": ["new-baby", "congratulations", "birthday"],
        "emotions": ["loved", "cherished", "celebrated"],
        "recipient_types": ["baby", "child", "parents"],
        "interests": ["home-decor"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Safe, hypoallergenic newborn essentials cherished by new mothers.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 15. ROYAL RESERVE & PREMIUM HAMPERS ──
    {
        "name": "Eternal Rose & Vanilla Soy Candle Chest",
        "subtitle": "Everlasting Preserved Rose in Carved Wooden Box",
        "description": "An everlasting preserved red velvet rose paired with a French vanilla scented soy candle in an engraved wooden gift chest.",
        "story": "A timeless keepsake designed to last for years without wilting.",
        "price": 1299,
        "original_price": 1699,
        "category_slug": "premium-gifts",
        "stock": 15,
        "images": ["https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80"],
        "tags": ["preserved-rose", "luxury", "keepsake", "candle", "anniversary", "wooden-box"],
        "occasions": ["anniversary", "wedding", "proposal", "love"],
        "emotions": ["loved", "cherished", "surprised"],
        "recipient_types": ["for-her", "partner", "wife"],
        "interests": ["flowers", "luxury", "home-decor"],
        "budget_tier": "1000-plus",
        "customizable": True,
        "same_day_available": False,
        "delivery_time_hours": 24,
        "preparation_time_minutes": 25,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Everlasting preserved keepsake with high emotional retention.",
        "location": "Rajahmundry, Vijayawada",
    },
    {
        "name": "Imperial Heritage Brass-Fitted Royal Chest",
        "subtitle": "Solid Sheesham Wood Chest with Belgian Truffles & Dry Fruits",
        "description": "An imperial hand-carved solid sheesham wood treasure chest with brass latches, holding 16 handcrafted Belgian pralines and 4 glass jars of roasted nuts and saffron honey.",
        "story": "Bloomora's pinnacle royal experience. An heirloom designed to stay in the family forever.",
        "price": 3499,
        "original_price": 4499,
        "category_slug": "premium-gifts",
        "stock": 10,
        "images": ["https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=800&q=80"],
        "tags": ["royal", "heritage", "chest", "luxury", "dry fruits", "truffles"],
        "occasions": ["wedding", "anniversary", "festivals", "congratulations"],
        "emotions": ["celebrated", "cherished", "loved"],
        "recipient_types": ["for-parents", "partner", "parents", "colleague"],
        "interests": ["luxury", "food"],
        "budget_tier": "1000-plus",
        "customizable": True,
        "same_day_available": False,
        "delivery_time_hours": 48,
        "preparation_time_minutes": 40,
        "is_best_seller": True,
        "is_trending": True,
        "ai_recommendation_reason": "Highest luxury tier artisanal chest for royal celebratory events.",
        "location": "Rajahmundry, Vijayawada",
    },

    # ── 16. GOURMET DRY FRUITS & SWEETS HAMPERS ──
    {
        "name": "Artisanal Roasted Dry Fruits & Honey-Glazed Almonds Tray",
        "subtitle": "Smoked Cashews, California Almonds, Afghan Raisins & Organic Honey",
        "description": "A handcrafted wooden geometric serving tray with 4 gold-rimmed airtight jars: peri-peri roasted cashews, salted California almonds, pistachios, and wildflower honey.",
        "story": "Healthy, nutritious, and undeniably gourmet.",
        "price": 799,
        "original_price": 999,
        "category_slug": "gourmet-hampers",
        "stock": 30,
        "images": ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80"],
        "tags": ["dry fruits", "nuts", "gourmet", "festive", "healthy", "hamper"],
        "occasions": ["festivals", "housewarming", "congratulations", "thank-you", "birthday"],
        "emotions": ["appreciated", "celebrated", "cherished"],
        "recipient_types": ["for-parents", "parents", "mother", "father", "colleague", "friend"],
        "interests": ["food", "fitness"],
        "budget_tier": "500-999",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 3,
        "preparation_time_minutes": 20,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Wholesome gourmet dry fruits in keepsake wooden serving tray.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },

    # ── 17. POCKET SURPRISES & QUICK GESTURES (UNDER 199) ──
    {
        "name": "The Gentle Pocket Gesture",
        "subtitle": "1 Dutch Rose + Cadbury Chocolate + Mini Card",
        "description": "One hand-picked Dutch Rose with Dairy Milk wrapped in soft blush paper with a delicate satin bow.",
        "story": "Small in price, massive in warmth. Designed for quick roadside pickups and spontaneous smiles.",
        "price": 149,
        "original_price": 199,
        "category_slug": "mini-gifts",
        "stock": 100,
        "images": ["https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80"],
        "tags": ["pocket-friendly", "rose", "chocolate", "student", "mini"],
        "occasions": ["thank-you", "sorry", "birthday", "love", "just-because"],
        "emotions": ["appreciated", "loved", "surprised"],
        "recipient_types": ["for-friends", "friend", "sibling", "colleague", "partner"],
        "interests": ["flowers", "chocolate"],
        "budget_tier": "under-199",
        "customizable": False,
        "same_day_available": True,
        "delivery_time_hours": 1,
        "preparation_time_minutes": 10,
        "is_best_seller": True,
        "is_trending": False,
        "ai_recommendation_reason": "Best pocket-friendly surprise under Rs.150 for student budgets.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
    {
        "name": "Sweet Smile Mini Token",
        "subtitle": "Cadbury Dairy Milk Silk + Handwritten Gold Mini Tag",
        "description": "A freshly wrapped Cadbury Dairy Milk Silk (60g) tied with gold satin ribbon and an embossed mini gift tag with your handwritten message.",
        "story": "A small sweet surprise that says 'I was thinking of you today'.",
        "price": 129,
        "original_price": 169,
        "category_slug": "mini-gifts",
        "stock": 80,
        "images": ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80"],
        "tags": ["chocolate", "mini", "pocket-friendly", "silk", "token"],
        "occasions": ["thank-you", "just-because", "birthday", "sorry"],
        "emotions": ["appreciated", "loved", "surprised"],
        "recipient_types": ["for-friends", "friend", "colleague", "sibling"],
        "interests": ["chocolate"],
        "budget_tier": "under-199",
        "customizable": True,
        "same_day_available": True,
        "delivery_time_hours": 1,
        "preparation_time_minutes": 10,
        "is_best_seller": False,
        "is_trending": True,
        "ai_recommendation_reason": "Sweetest pocket token under Rs.150 with personalized handwritten tag.",
        "location": "Surampalem, Rajahmundry, Vijayawada",
    },
]


class Command(BaseCommand):
    help = "Seed Bloomora database with categories, occasions, sellers, and products"

    @transaction.atomic
    def handle(self, *args, **options):
        from apps.catalog.models import Category, Occasion, Product
        from apps.creators.models import Seller
        from apps.accounts.models import User
        from apps.taxonomy.models import GiftType

        self.stdout.write(self.style.SUCCESS("[Bloomora] Seeding database with all gift types..."))

        # 1. Categories
        self.stdout.write("  Creating/updating categories...")
        category_map = {}
        for cat_data in CATEGORIES:
            cat, _ = Category.objects.update_or_create(
                slug=cat_data["slug"],
                defaults={
                    "name": cat_data["name"],
                    "icon": cat_data["icon"],
                    "description": cat_data["description"],
                    "sort_order": cat_data["sort_order"],
                    "active": True,
                }
            )
            category_map[cat_data["slug"]] = cat

        # 2. Occasions
        self.stdout.write("  Creating/updating occasions...")
        occasion_map = {}
        for occ_data in OCCASIONS:
            occ, _ = Occasion.objects.update_or_create(
                slug=occ_data["slug"],
                defaults={"name": occ_data["name"], "emoji": occ_data["emoji"], "active": True}
            )
            occasion_map[occ_data["slug"]] = occ

        # 3. Demo Seller
        self.stdout.write("  Ensuring demo seller...")
        seller_user, _ = User.objects.get_or_create(
            email="seller@bloomora.com",
            defaults={
                "first_name": "Bloomora",
                "last_name": "Creator",
                "role": "seller",
                "is_active": True,
            }
        )
        if not seller_user.has_usable_password():
            seller_user.set_password("Bloomora@2026")
            seller_user.save()

        seller, _ = Seller.objects.get_or_create(
            user=seller_user,
            defaults={
                "business_name": "Bloomora Signature Collection",
                "description": "Bloomora's own curated collection of premium gifts.",
                "location": "Rajahmundry, Andhra Pradesh",
                "approved": True,
                "creator_story": "Bloomora's founding collection, curated with love from Andhra Pradesh.",
                "handmade": True,
                "supports_customization": True,
                "supports_same_day": True,
                "lead_time_hours": 2,
                "rating": 4.95,
                "total_orders": 847,
            }
        )

        # 4. Products
        self.stdout.write("  Creating/updating products across all gift types...")
        created_count = 0
        updated_count = 0
        for prod_data in PRODUCTS_DATA:
            category = category_map.get(prod_data["category_slug"])
            if not category:
                continue

            product, created = Product.objects.update_or_create(
                name=prod_data["name"],
                defaults={
                    "seller": seller,
                    "subtitle": prod_data.get("subtitle", ""),
                    "description": prod_data["description"],
                    "story": prod_data.get("story", ""),
                    "price": prod_data["price"],
                    "original_price": prod_data.get("original_price"),
                    "category": category,
                    "stock": prod_data["stock"],
                    "images": prod_data["images"],
                    "tags": prod_data["tags"],
                    "emotions": prod_data.get("emotions", []),
                    "recipient_types": prod_data.get("recipient_types", []),
                    "interests": prod_data.get("interests", []),
                    "budget_tier": prod_data.get("budget_tier", ""),
                    "customizable": prod_data.get("customizable", False),
                    "supports_photo_customization": prod_data.get("supports_photo_customization", False),
                    "supports_text_customization": prod_data.get("supports_text_customization", False),
                    "same_day_available": prod_data.get("same_day_available", False),
                    "delivery_time_hours": prod_data.get("delivery_time_hours", 24),
                    "preparation_time_minutes": prod_data.get("preparation_time_minutes", 30),
                    "is_best_seller": prod_data.get("is_best_seller", False),
                    "is_trending": prod_data.get("is_trending", False),
                    "ai_recommendation_reason": prod_data.get("ai_recommendation_reason", ""),
                    "location": prod_data.get("location", ""),
                    "active": True,
                    "featured": prod_data.get("is_best_seller", False),
                }
            )

            # Link occasions
            product.occasions.clear()
            for occ_slug in prod_data.get("occasions", []):
                if occ_slug in occasion_map:
                    product.occasions.add(occasion_map[occ_slug])

            # Link taxonomy gift types if existing
            matching_gift_types = GiftType.objects.filter(slug__iexact=prod_data["category_slug"])
            if matching_gift_types.exists():
                product.gift_types.set(matching_gift_types)

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(f"  Processed {created_count + updated_count} products ({created_count} created, {updated_count} updated)."))
        self.stdout.write(self.style.SUCCESS("\nBloomora database successfully seeded with all types of gifts!"))
