# Generated by Django 5.1.15 on 2026-09-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bloomora_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bloomora_occasions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('customizable', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('story', models.TextField(blank=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emotions', models.JSONField(default=list)),
                ('recipient_types', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('budget_tier', models.CharField(blank=True, max_length=20)),
                ('supports_photo_customization', models.BooleanField(default=False)),
                ('supports_text_customization', models.BooleanField(default=False)),
                ('personalization_fields', models.JSONField(default=list)),
                ('same_day_available', models.BooleanField(default=False)),
                ('delivery_time_hours', models.IntegerField(default=24)),
                ('delivery_area', models.JSONField(default=list)),
                ('preparation_time_minutes', models.IntegerField(default=30)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('ai_recommendation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('occasions', models.ManyToManyField(blank=True, related_name='products', to='catalog.occasion')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creators.seller')),
            ],
            options={
                'db_table': 'bloomora_products',
                'ordering': ['-featured', '-is_best_seller', '-created_at'],
                'indexes': [models.Index(fields=['active', 'category'], name='bloomora_pr_active_71baaa_idx'), models.Index(fields=['price'], name='bloomora_pr_price_10cda7_idx'), models.Index(fields=['location'], name='bloomora_pr_locatio_f75841_idx'), models.Index(fields=['seller'], name='bloomora_pr_seller__e1318d_idx')],
            },
        ),
    ]
