# Generated by Django 5.1.15 on 2026-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_intent_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='taxonomy.giftintenttag'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='taxonomy.gifttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='taxonomy.occasiontype'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipient_type_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='taxonomy.recipienttype'),
        ),
    ]
