# Generated by Django 5.1.15 on 2026-09-14 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurprisePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('occasion', models.CharField(max_length=100)),
                ('emotion', models.CharField(blank=True, max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.JSONField(default=dict)),
                ('gift_message', models.TextField(blank=True)),
                ('packaging_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('cake_description', models.CharField(blank=True, max_length=200)),
                ('flowers_description', models.CharField(blank=True, max_length=200)),
                ('decorations_description', models.CharField(blank=True, max_length=200)),
                ('food_description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloomora_surprises',
                'ordering': ['-created_at'],
            },
        ),
    ]
