# Generated by Django 5.1.15 on 2026-09-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftIntentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bloomora_gift_intent_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bloomora_recipient_types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('image', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='taxonomy.gifttype')),
            ],
            options={
                'db_table': 'bloomora_gift_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='bloomora_gi_slug_1026ed_idx'), models.Index(fields=['parent', 'is_active'], name='bloomora_gi_parent__f8cc70_idx'), models.Index(fields=['display_order'], name='bloomora_gi_display_06ab7d_idx'), models.Index(fields=['is_featured', 'is_active'], name='bloomora_gi_is_feat_e5d6c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OccasionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('image', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='taxonomy.occasiontype')),
            ],
            options={
                'db_table': 'bloomora_occasion_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='bloomora_oc_slug_afef91_idx'), models.Index(fields=['parent', 'is_active'], name='bloomora_oc_parent__4f0a73_idx'), models.Index(fields=['is_featured', 'is_active'], name='bloomora_oc_is_feat_8b547c_idx')],
            },
        ),
    ]
