export interface Product {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  story: string;
  price: number;
  originalPrice?: number;
  category: string;
  occasion: string[];
  recipientTag: 'for-her' | 'for-him' | 'for-parents' | 'for-friends' | 'for-colleagues';
  budgetTier: 'under-199' | '200-299' | '300-499' | '500-999' | '1000-plus';
  images: string[];
  packagingItems: string[];
  rating: number;
  reviewCount: number;
  isBestSeller?: boolean;
  isTrending?: boolean;
  isSeasonal?: boolean;
  isFeatured?: boolean;
  inStock: boolean;
  preparationTimeMinutes: number;
  aiRecommendationReason: string;
  partnerId?: string;
  externalProductUrl?: string;
  isSponsored?: boolean;
  isPartnerProduct?: boolean;
  isBloomoraProduct?: boolean;
}

export interface PartnerShop {
  id: string;
  name: string;
  type: 'Flower Shop' | 'Bakery' | 'Gift Store' | 'Cafe' | 'Stationery';
  city: string;
  area: string;
  address: string;
  landmark: string;
  rating: number;
  distanceKm: number;
  openHours: string;
  phone: string;
  image: string;
  availableLockers: number;
  isStoreOpen: boolean;
  deliveryZones: string[];
}

export interface Coupon {
  code: string;
  discountPercentage: number;
  maxDiscount: number;
  minOrderValue: number;
  description: string;
}

export interface GiftComboRecommendation {
  id: string;
  title: string;
  reasoning: string;
  totalPrice: number;
  budget: number;
  savings: number;
  items: {
    name: string;
    quantity: number;
    price: number;
    image: string;
  }[];
  packaging: string;
  recommendedCardMessage: string;
}

export interface CategoryItem {
  id: string;
  name: string;
  icon: string;
  description: string;
  image: string;
  itemCount: string;
  tag: string;
}

export const CATEGORIES: CategoryItem[] = [
  {
    id: 'flowers',
    name: 'Floral Arrangements',
    icon: 'Flower2',
    description: 'Fresh Dutch roses & hand-tied artisanal floral compositions',
    image: '/products/flowers/default/12-red-flowers-bouquet-1.png',
    itemCount: '12+ Arrangements',
    tag: 'Fresh Daily',
  },
  {
    id: 'bouquets',
    name: 'Velvet Box Bouquets',
    icon: 'Gift',
    description: 'Handcrafted floral art presented in signature cylindrical velvet boxes',
    image: '/products/bouquets/default/velvet-box-arrangement.png',
    itemCount: '9 Styles',
    tag: 'Signature Wrap',
  },
  {
    id: 'cakes',
    name: 'Gourmet Bento Cakes',
    icon: 'Cake',
    description: 'Artisanal single-portion chocolate truffle cakes & patisserie creations',
    image: '/products/cakes/default/bento-chocolate-truffle-mini-cake-1.png',
    itemCount: '9 Flavors',
    tag: 'Freshly Baked',
  },
  {
    id: 'chocolate-bouquets',
    name: 'Chocolate Bouquets',
    icon: 'Sparkles',
    description: 'Ferrero Rocher & Swiss truffles paired with satin roses in keepsake boxes',
    image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80',
    itemCount: '8 Collections',
    tag: 'Sweet Indulgence',
  },
  {
    id: 'corporate-gifts',
    name: 'Corporate & Executive',
    icon: 'Briefcase',
    description: 'Debossed leather journals, precision pens, onboarding kits & client sets',
    image: '/products/corporate/executive-gift-set/executive-gift-set.png',
    itemCount: '6 Sets',
    tag: 'Executive B2B',
  },
  {
    id: 'kids-gifting',
    name: 'Kids Art & Craft Hampers',
    icon: 'Palette',
    description: 'Age-tiered creative hampers fostering tactile exploration, painting & DIY',
    image: '/products/kids/junior-creator-craft-hamper-ages-5-7/junior-creator-craft-hamper-ages-5-7.png',
    itemCount: '4 Age Tiers',
    tag: 'Ages 2–14+',
  },
  {
    id: 'premium-gifts',
    name: 'Royal Reserve Hampers',
    icon: 'Crown',
    description: 'Handcrafted solid wood chests, gourmet dry fruits & Belgian truffles',
    image: '/products/premium/imperial-heritage-hamper/whatsapp-image-2026-09-14-at-5-16-43-pm-1.jpeg',
    itemCount: '3 Luxury Tiers',
    tag: 'Heirloom Keepsake',
  },
  {
    id: 'custom-gifts',
    name: 'Custom Keepsakes & Mugs',
    icon: 'Coffee',
    description: 'High-fired handcrafted ceramic mugs and personalized memory gifts',
    image: '/products/general-gifts/default/custom_ceramic_mug.jpg',
    itemCount: '10 Designs',
    tag: 'Personalized',
  },
];

export const OCCASIONS = [
  { id: 'birthday', name: 'Birthday Celebration', color: 'from-amber-100 to-rose-100' },
  { id: 'love', name: 'Love & Romance', color: 'from-rose-100 to-red-100' },
  { id: 'anniversary', name: 'Anniversary Milestone', color: 'from-amber-200 to-yellow-100' },
  { id: 'proposal', name: 'Proposal Moment', color: 'from-pink-100 to-rose-200' },
  { id: 'congratulations', name: 'Congratulations', color: 'from-emerald-100 to-teal-100' },
  { id: 'thank-you', name: 'Gratitude & Care', color: 'from-purple-100 to-pink-100' },
];

export const EMOTIONAL_COLLECTIONS = [
  { id: 'for-her', title: 'For Her', description: 'Elegance & romantic charm' },
  { id: 'for-him', title: 'For Him', description: 'Refined & thoughtful keepsakes' },
  { id: 'for-parents', title: 'For Parents', description: 'Warmth & timeless gratitude' },
  { id: 'for-friends', title: 'For Best Friends', description: 'Joyful & sweet celebrations' },
  { id: 'for-colleagues', title: 'For Colleagues & Mentors', description: 'Executive polish and professional appreciation' },
  { id: 'student-budget', title: 'Student Budget', description: 'Pocket-friendly luxury under ₹299' },
  { id: 'hidden-gems', title: 'Hidden Gems', description: 'Unique AI curated combinations' },
];

export const BUDGET_TIERS = [
  { id: 'under-199', label: 'Under ₹199', title: 'Tiny Surprises', subtitle: 'Perfect for students & quick thank-yous', range: [0, 199], badge: 'Pocket Friendly' },
  { id: '200-299', label: '₹200 - ₹299', title: 'Chocolate Moments', subtitle: 'Luxury wrapping included with sweet treats', range: [200, 299], badge: 'Most Popular' },
  { id: '300-499', label: '₹300 - ₹499', title: 'Romantic Classics', subtitle: 'Most loved combination hampers', range: [300, 499], badge: 'Best Value' },
  { id: '500-999', label: '₹500 - ₹999', title: 'Grand Celebrations', subtitle: 'Multi-item keepsakes & truffle boxes', range: [500, 999], badge: 'Premium Hampers' },
  { id: '1000-plus', label: '₹1000+', title: 'Ultimate Luxury Chests', subtitle: 'Carved wooden boxes & preserved roses', range: [1000, 10000], badge: 'Royal Luxury' },
];

export const COUPONS: Coupon[] = [
  { code: 'BLOOM100', discountPercentage: 20, maxDiscount: 100, minOrderValue: 249, description: 'Flat 20% off on your first AI curated gift story' },
  { code: 'MEETME10', discountPercentage: 100, maxDiscount: 10, minOrderValue: 199, description: 'Free Pickup Fee on Meet Me There orders' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'A Beautiful Birthday Surprise',
    subtitle: '2 Dutch Red Roses + Dairy Milk Silk + Gold Ribbon',
    description: 'Two long-stem Dutch red roses paired with Cadbury Dairy Milk Silk (60g), wrapped in soft ivory matte paper with a signature gold velvet ribbon and custom gold foil greeting card.',
    story: 'Designed to transform a modest ₹249 budget into a moment of pure unboxing joy. AI selected this because it pairs fresh floral fragrance with sweet indulgence.',
    price: 249,
    originalPrice: 349,
    category: 'flowers',
    occasion: ['love', 'birthday', 'proposal', 'anniversary'],
    recipientTag: 'for-her',
    budgetTier: '200-299',
    images: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=80',
    ],
    packagingItems: ['Ivory Matte Wrap', 'Gold Velvet Ribbon', 'Gold Embossed Card'],
    rating: 4.9,
    reviewCount: 312,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: true,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Optimal visual balance of flowers & chocolates within ₹250 budget.',
  },
  {
    id: 'prod-2',
    name: 'The Golden Truffle & Satin Treasure',
    subtitle: '16 Golden Ferrero Truffles in Cylinder Box',
    description: '16 golden Ferrero Rocher pralines intricately woven with artificial cream satin roses in a rigid midnight black and gold foil cylinder box.',
    story: 'Created for grand milestones. Loved for anniversaries and celebrations where elegance meets indulgence.',
    price: 899,
    originalPrice: 1199,
    category: 'chocolate-bouquets',
    occasion: ['anniversary', 'birthday', 'wedding', 'congratulations'],
    recipientTag: 'for-her',
    budgetTier: '500-999',
    images: [
      'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    ],
    packagingItems: ['Midnight Black Rigid Box', 'Satin Roses', 'Rose Gold Ribbon'],
    rating: 5.0,
    reviewCount: 489,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 20,
    aiRecommendationReason: 'Highest luxury rating for milestone anniversaries & grand celebrations.',
  },
  {
    id: 'prod-3',
    name: 'The Gentle Pocket Gesture',
    subtitle: '1 Dutch Rose + Cadbury Chocolate + Mini Card',
    description: 'One hand-picked Dutch Rose with Dairy Milk (13.2g) wrapped in soft blush paper with a delicate satin bow and mini card.',
    story: 'Small in price, massive in warmth. Designed for quick roadside pickups and spontaneous smiles.',
    price: 149,
    originalPrice: 199,
    category: 'flowers',
    occasion: ['thank-you', 'birthday', 'love'],
    recipientTag: 'for-friends',
    budgetTier: 'under-199',
    images: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    packagingItems: ['Soft Blush Paper', 'Satin Bow', 'Handwritten Tag'],
    rating: 4.8,
    reviewCount: 184,
    isBestSeller: false,
    isTrending: false,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 10,
    aiRecommendationReason: 'Best pocket-friendly surprise under ₹150 for student budgets.',
  },
  {
    id: 'prod-4',
    name: 'Eternal Rose & Vanilla Soy Candle Chest',
    subtitle: 'Everlasting Preserved Rose in Carved Wooden Box',
    description: 'An everlasting preserved red velvet rose paired with a French vanilla scented soy candle in an engraved wooden gift chest.',
    story: 'A timeless keepsake designed to last for years. Perfect for milestone anniversaries or grand declarations.',
    price: 1299,
    originalPrice: 1699,
    category: 'premium-gifts',
    occasion: ['anniversary', 'wedding', 'proposal', 'love'],
    recipientTag: 'for-her',
    budgetTier: '1000-plus',
    images: [
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=800&q=80',
    ],
    packagingItems: ['Carved Wooden Chest', 'Silk Lining', 'Vanilla Soy Candle'],
    rating: 4.95,
    reviewCount: 204,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: true,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 25,
    aiRecommendationReason: 'Everlasting preserved keepsake with high emotional retention.',
  },
  {
    id: 'prod-5',
    name: 'Sweet Celebration Gift Tray',
    subtitle: '3 Roses + Cadbury Celebrations + Sparkler',
    description: 'Three vibrant Dutch roses, Cadbury Celebrations pack (113g), a luxury birthday greeting card, and a golden party sparkler.',
    story: "Everything needed to light up someone's birthday instantly. Prepared with love by local partner bakeries & flower studios.",
    price: 449,
    originalPrice: 599,
    category: 'custom-gifts',
    occasion: ['birthday', 'congratulations'],
    recipientTag: 'for-friends',
    budgetTier: '300-499',
    images: [
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
    ],
    packagingItems: ['Luxury Kraft Tray', 'Cadbury Celebrations', 'Golden Sparkler'],
    rating: 4.87,
    reviewCount: 350,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Top rated birthday celebration combo with golden party sparkler.',
  },

  // 2. NEW CATEGORY: BOUQUETS (VELVET BOX ARRANGEMENT)
  {
    id: 'prod-bouquet-velvet',
    name: 'Signature Velvet Box Rose Arrangement',
    subtitle: 'Handcrafted Premium Roses in Matte Cylindrical Velvet Hatbox',
    description: 'A breathtaking cylindrical velvet box filled with hand-selected long-stem roses, delicate baby’s breath, and bespoke greenery. Built on an internal floral hydration core so blooms stay garden-fresh for days.',
    story: 'Crafted for high-emotion milestones. The deep tactile velvet exterior transforms an ordinary bouquet into a regal luxury keepsake that decorates any dressing table or desk.',
    price: 1499,
    originalPrice: 1999,
    category: 'bouquets',
    occasion: ['anniversary', 'proposal', 'birthday', 'love'],
    recipientTag: 'for-her',
    budgetTier: '1000-plus',
    images: ["/products/bouquets/default/velvet-box-arrangement-2.png", "/products/bouquets/default/velvet-box-arrangement-3.png", "/products/bouquets/default/velvet-box-arrangement-4.png", "/products/bouquets/default/velvet-box-arrangement-5.png", "/products/bouquets/default/velvet-box-arrangement-6.png", "/products/bouquets/default/velvet-box-arrangement-7.png", "/products/bouquets/default/velvet-box-arrangement-8.png", "/products/bouquets/default/velvet-box-arrangement-9.png", "/products/bouquets/default/velvet-box-arrangement.png"],
    packagingItems: ['Signature Cylindrical Velvet Hatbox', 'Gold Foil Embossed Crest', 'Satin Pull Ribbon', 'Hydration Core Pad', 'Handwritten Calligraphy Card'],
    rating: 4.96,
    reviewCount: 248,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: true,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 25,
    aiRecommendationReason: 'Most awarded floral presentation architecture for romantic celebrations.',
  },

  // 3. NEW CATEGORY: CAKES (BENTO CHOCOLATE TRUFFLE)
  {
    id: 'prod-cake-bento',
    name: 'Bento Belgian Dark Chocolate Truffle Cake',
    subtitle: 'Artisanal Single-Portion Mini Cake with 55% Cocoa Ganache',
    description: 'Rich, moist layers of dark cocoa sponge enrobed in silky 55% Belgian chocolate ganache. Specially baked fresh daily in a 4-inch bento format, complete with candle and wooden cutlery.',
    story: 'Inspired by modern minimalist pastry culture. Perfect for intimate birthdays, spontaneous congratulations, or midnight desk surprises where grand cakes go to waste.',
    price: 399,
    originalPrice: 499,
    category: 'cakes',
    occasion: ['birthday', 'congratulations', 'love', 'thank-you'],
    recipientTag: 'for-friends',
    budgetTier: '300-499',
    images: ["/products/cakes/default/bento-chocolate-truffle-mini-cake-1.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-2.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-3.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-4.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-5.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-6.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-7.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-8.png", "/products/cakes/default/bento-chocolate-truffle-mini-cake-9.png"],
    packagingItems: ['Eco-Friendly Sugarcane Bento Box', 'Custom Pastel Wax Ribbon', 'Pastel Party Candle', 'Birchwood Tasting Fork', 'Gold Embossed Story Note'],
    rating: 4.93,
    reviewCount: 420,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 20,
    aiRecommendationReason: 'Optimal single-celebration dessert pairing premium taste with zero food waste.',
  },

  // 4. NEW FLORAL ADDITION: 12 RED ROSES BOUQUET
  {
    id: 'prod-flower-12roses',
    name: '12 Red Roses Luxe Botanical Bouquet',
    subtitle: '12 Long-Stem Fresh Dutch Red Roses with Gypsophila & Golden Wrap',
    description: 'Twelve flawless Grade-A Dutch red roses hand-tied by master florists with fresh gypsophila (baby’s breath) and eucalyptus foliage, enveloped in dual-layer waterproof matte paper and golden satin ribbon.',
    story: 'Twelve roses carry a universal language: “Be mine, completely.” Sourced directly from climate-controlled partner greenhouses in Ooty and Bangalore.',
    price: 599,
    originalPrice: 799,
    category: 'flowers',
    occasion: ['love', 'anniversary', 'birthday', 'proposal'],
    recipientTag: 'for-her',
    budgetTier: '500-999',
    images: ["/products/flowers/default/12-red-flowers-bouquet-1.png", "/products/flowers/default/12-red-flowers-bouquet-2.png", "/products/flowers/default/12-red-flowers-bouquet-3.png", "/products/flowers/default/12-red-flowers-bouquet-4.png", "/products/flowers/default/12-red-flowers-bouquet-5.png", "/products/flowers/default/12-red-flowers-bouquet-6.png", "/products/flowers/default/12-red-flowers-bouquet-7.png"],
    packagingItems: ['Dual-Tone Parisian Matte Kraft Paper', 'Metallic Gold Satin Ribbon', 'Flower Food Nutrient Sachet', 'Custom Letterpress Envelope & Card'],
    rating: 4.95,
    reviewCount: 392,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Timeless floral classic with high aesthetic consistency and long vase life.',
  },

  // 5. NEW GENERAL GIFTS: CUSTOM CERAMIC MUG
  {
    id: 'prod-general-mug',
    name: 'Artisanal Hand-Glazed Ceramic Keepsake Mug',
    subtitle: 'Ergonomic 350ml Stoneware Mug with Custom Name Engraving Option',
    description: 'Fired at 1280°C for exceptional durability and chip-resistance. Features an ergonomic thumb rest, organic speckled matte exterior, smooth glazed lip, and optional personalized gold monogramming.',
    story: 'Designed to be held with both hands on quiet mornings. Whether for artisan coffee or evening chai, this mug turns a daily ritual into a comforting memory of who gave it.',
    price: 299,
    originalPrice: 399,
    category: 'custom-gifts',
    occasion: ['thank-you', 'birthday', 'friendship'],
    recipientTag: 'for-colleagues',
    budgetTier: '200-299',
    images: ["/products/general-gifts/default/custom_ceramic_mug.jpg", "/products/general-gifts/default/custom_ceramic_mug_10.jpeg", "/products/general-gifts/default/custom_ceramic_mug_2.jpg", "/products/general-gifts/default/custom_ceramic_mug_3.jpg", "/products/general-gifts/default/custom_ceramic_mug_4.jpeg", "/products/general-gifts/default/custom_ceramic_mug_5.jpeg", "/products/general-gifts/default/custom_ceramic_mug_6.jpeg", "/products/general-gifts/default/custom_ceramic_mug_7.jpeg", "/products/general-gifts/default/custom_ceramic_mug_8.jpeg", "/products/general-gifts/default/custom_ceramic_mug_9.jpeg"],
    packagingItems: ['Sturdy Kraft Protective Box', 'Eco Recycled Paper Cushioning', 'Ceramic Care & Microwave Guide', 'Wax-Sealed Friendship Card'],
    rating: 4.89,
    reviewCount: 182,
    isBestSeller: false,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Best high-utility keepsake under ₹300 with personalized daily sentiment.',
  },

  // 6. CORPORATE GIFTING (TASK1)
  {
    id: 'prod-corp-diary-pen',
    name: 'Executive Vegan Leather Diary & Pen Set',
    subtitle: 'Debossed A5 Hardcover Notebook + Heavy German Ink Rollerball Pen',
    description: 'An executive set featuring a 192-page ruled journal with 100gsm ink-proof ivory paper, pen loop, ribbon bookmark, inner document pocket, and a precision-weighted metallic rollerball pen.',
    story: 'From our Corporate Persona collection. Handpicked for team leaders, graduating scholars, and business innovators who value tactile focus and elegance.',
    price: 499,
    originalPrice: 799,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'thank-you', 'anniversary'],
    recipientTag: 'for-colleagues',
    budgetTier: '300-499',
    images: ["/products/corporate/diary-pen-set/diary-pen-set.png", "/products/corporate/diary-pen-set/magnific_a-close-editorial-photogr_ovbglag829.png", "/products/corporate/diary-pen-set/magnific_a-diary-and-pen-gift-set-_n2vxi8u6d9.png", "/products/corporate/diary-pen-set/magnific_a-diary-and-pen-gift-set-_vxfnk5cmmu.png", "/products/corporate/diary-pen-set/magnific_a-diary-and-pen-set-displ_klyi22zkqp.png", "/products/corporate/diary-pen-set/magnific_a-diary-and-pen-set-stage_79zqpp8jal.png", "/products/corporate/diary-pen-set/magnific_an-editorial-photograph-f_8a5zggtiru.png", "/products/corporate/diary-pen-set/magnific_commercial-studio-4k-pack_juiw1xpld0.png", "/products/corporate/diary-pen-set/magnific_commercial-studio-4k-pack_rgnskxzxtc.png"],
    packagingItems: ['Debossed Gift Sleeve Box', 'A5 Hardbound Vegan Leather Journal', 'Matte Black Rollerball Pen', 'Metallic Clip Bookmark', 'Corporate Blessing Card'],
    rating: 4.91,
    reviewCount: 156,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Refined corporate gift under ₹500 with zero lead-time customization.',
  },
  {
    id: 'prod-corp-mug-pen-diary',
    name: 'Executive Desk Trio: Ceramic Mug, Diary & Pen',
    subtitle: 'Ceramic Workstation Mug + A5 Leather Planner + Gunmetal Pen',
    description: 'A cohesive three-piece desk set featuring a matte minimalist ceramic mug (350ml), an undated executive planner with monthly and weekly spreads, and a gunmetal ballpoint pen nestled in custom EVA foam.',
    story: 'The ultimate daily workstation companion. Designed to keep professionals organized, caffeinated, and inspired throughout demanding workdays.',
    price: 899,
    originalPrice: 1200,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'thank-you', 'birthday'],
    recipientTag: 'for-colleagues',
    budgetTier: '500-999',
    images: ["/products/corporate/mug-pen-diary/mug-pen-diary.png", "/products/corporate/mug-pen-diary/magnific_availablelight-photograph_doeijlmpcl.png", "/products/corporate/mug-pen-diary/magnific_availablelight-photograph_ju6a00yld0.png", "/products/corporate/mug-pen-diary/magnific_ecommerce-product-photogr_dou8v4apcl.png", "/products/corporate/mug-pen-diary/magnific_studiolike-desk-scene-of-_o6y5ortynm.png"],
    packagingItems: ['Custom Moulded Presentation Box', 'Matte Ceramic Desk Mug', 'Hardbound Executive Journal', 'Gunmetal Twist Pen', 'Personalized Desk Card'],
    rating: 4.94,
    reviewCount: 114,
    isBestSeller: true,
    isTrending: false,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 20,
    aiRecommendationReason: 'Best-rated desk lifestyle set balancing utility, comfort, and professional prestige.',
  },
  {
    id: 'prod-corp-bottle-diary-pen',
    name: 'Hydration & Productivity Executive Set',
    subtitle: 'Double-Wall Insulated Bottle + Hardcover Journal + Precision Stylus Pen',
    description: 'A 500ml food-grade 304 stainless steel thermal bottle that preserves beverage heat for 12 hours or cold for 24 hours, paired with a debossed A5 notebook and dual-function stylus ballpoint pen.',
    story: 'Engineered for dynamic professionals who transition seamlessly between the boardroom, fitness studio, and travel hubs.',
    price: 1199,
    originalPrice: 1500,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'thank-you', 'birthday'],
    recipientTag: 'for-colleagues',
    budgetTier: '1000-plus',
    images: ["/products/corporate/mug-pen-diary-bottle-diary-pen/bottle-diary-pen.png", "/products/corporate/mug-pen-diary-bottle-diary-pen/magnific_matteblack-insulated-wate_igdlf5x3uk.png", "/products/corporate/mug-pen-diary-bottle-diary-pen/magnific_premium-sliding-gift-box-_79zqbfejal.png"],
    packagingItems: ['Thermal Insulated Flask (500ml)', 'Hardcover Grid/Ruled Journal', 'Precision Metallic Stylus Pen', 'Rigid Magnetic Presentation Chest'],
    rating: 4.92,
    reviewCount: 98,
    isBestSeller: false,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 20,
    aiRecommendationReason: 'Top choice for employee health and executive productivity wellness.',
  },
  {
    id: 'prod-corp-welcome-kit',
    name: 'Employee Welcome & Onboarding Kit',
    subtitle: 'Commuter Laptop Backpack + Thermal Bottle + Hardbound Journal + Pen',
    description: 'The definitive first-day onboarding hamper. Includes an ergonomic water-resistant 15.6-inch laptop backpack, double-wall insulated tumbler, executive organizer, and signature metal pen.',
    story: 'The first impression of an employer lasts for years. Created to make day-one for new engineers, designers, and managers feel like joining a world-class team.',
    price: 1699,
    originalPrice: 2000,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'thank-you'],
    recipientTag: 'for-colleagues',
    budgetTier: '1000-plus',
    images: ["/products/corporate/employee-welcome-kit/employee-welcome-kit.png", "/products/corporate/employee-welcome-kit/magnific_commercial-studio-4k-prod_9zv2sxgnyz.png", "/products/corporate/employee-welcome-kit/magnific_editorial-photograph-of-a_ifknpbitve.png", "/products/corporate/employee-welcome-kit/magnific_open-unboxing-shot-of-a-c_ifknyjktve.png"],
    packagingItems: ['Modular Laptop Commuter Bag', 'Vacuum Insulated Flask', 'Hardcover A5 Planner', 'Heavy Metal Ballpoint Pen', 'Welcome Onboarding Certificate Card'],
    rating: 4.98,
    reviewCount: 135,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 30,
    aiRecommendationReason: 'Gold standard corporate HR welcome kit for talent retention.',
  },
  {
    id: 'prod-corp-executive-set',
    name: 'Boardroom Executive Portfolio Set',
    subtitle: 'Zippered Leather Portfolio + Calculator + Luxury Pen + Tech Card Sleeve',
    description: 'A professional executive leather folder with tablet/document sleeve, solar dual-power calculator, business card organizer, memo block, and German-engineered rollerball pen.',
    story: 'Brought to board meetings and investor presentations. Built for leaders whose signatures seal transformative partnerships.',
    price: 2299,
    originalPrice: 3000,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'anniversary'],
    recipientTag: 'for-colleagues',
    budgetTier: '1000-plus',
    images: ["/products/corporate/executive-gift-set/executive-gift-set.png", "/products/corporate/executive-gift-set/whatsapp-image-2026-09-14-at-4-58-26-pm.jpeg", "/products/corporate/executive-gift-set/whatsapp-image-2026-09-14-at-4-58-42-pm.jpeg", "/products/corporate/executive-gift-set/whatsapp-image-2026-09-14-at-4-58-59-pm.jpeg", "/products/corporate/executive-gift-set/whatsapp-image-2026-09-14-at-4-59-39-pm.jpeg", "/products/corporate/executive-gift-set/magnific_boardroom-table-closeup-t_vqjhv3ia47.png"],
    packagingItems: ['Zippered Vegan Leather Padfolio', 'Solar Executive Calculator', 'Brass Rollerball Pen', 'Metallic Card Case', 'Luxe Black Presentation Gift Box'],
    rating: 4.96,
    reviewCount: 72,
    isBestSeller: false,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 25,
    aiRecommendationReason: 'Conveys executive distinction and functional authority for senior leadership.',
  },
  {
    id: 'prod-corp-premium-hamper',
    name: 'Grand Corporate Celebration Hamper',
    subtitle: 'Artisanal Chocolates + Roasted California Almonds + Executive Essentials',
    description: 'An expansive celebratory wooden crate featuring California slow-roasted almonds, imported dark chocolate truffles, organic forest honey, executive brass pen, and luxury leather-bound journal.',
    story: 'Reserved for company milestones, year-end celebrations, and high-value client relationship renewals.',
    price: 3499,
    originalPrice: 5000,
    category: 'corporate-gifts',
    occasion: ['congratulations', 'anniversary', 'thank-you'],
    recipientTag: 'for-colleagues',
    budgetTier: '1000-plus',
    images: ["/products/corporate/premimum-corporate-hamper/premium-corporate-hamper.png", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-50-48-pm.jpeg", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-51-32-pm.jpeg", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-51-50-pm.jpeg", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-52-07-pm.jpeg", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-52-51-pm.jpeg", "/products/corporate/premimum-corporate-hamper/whatsapp-image-2026-09-14-at-4-52-55-pm.jpeg", "/products/corporate/premimum-corporate-hamper/magnific_a-wooden-cratestyle-premi_jnyirhhoq4.png", "/products/corporate/premimum-corporate-hamper/magnific_an-elegant-black-leather-_nvtd9r8yqd.png", "/products/corporate/premimum-corporate-hamper/magnific_editorial-photograph-of-a_upaforpwny.png"],
    packagingItems: ['Natural Wood Keepsake Chest with Brass Clasp', 'Gourmet Almonds Glass Jar (200g)', 'Belgian Truffles Box', 'Brass Executive Pen', 'Hardcover Journal', 'Wax-Sealed Congratulations Scroll'],
    rating: 4.99,
    reviewCount: 88,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 35,
    aiRecommendationReason: 'Highest prestige ranking for milestone client gifting and executive appreciation.',
  },

  // 7. KIDS GIFTING: ART & CRAFT LEARNING HAMPERS (TASK1)
  {
    id: 'prod-kids-toddler',
    name: 'Toddler Sensory Explorer Hamper (Ages 2–4)',
    subtitle: 'Organic Playdough, Chunky Beeswax Crayons & Wooden Stamp Rollers',
    description: 'An educational tactile hamper crafted for toddlers. Features 3 jars of food-grade organic scent-free playdough, ergonomic palm-grip pure beeswax crayons, washable finger paints, and wooden texture rollers.',
    story: 'From our Kids Gifting Art & Craft series. Designed by early child development specialists to nurture tactile discovery and palm grip motor coordination without mobile screens.',
    price: 799,
    originalPrice: 950,
    category: 'kids-gifting',
    occasion: ['birthday', 'congratulations'],
    recipientTag: 'for-friends',
    budgetTier: '500-999',
    images: ["/products/kids/toddler-sensory-explorer-hamper-ages-2-4/toddler-sensory-explorer-hamper-ages-2-4.png", "/products/kids/toddler-sensory-explorer-hamper-ages-2-4/magnific_bright-4k-commercial-prod_juiwknuld0.png", "/products/kids/toddler-sensory-explorer-hamper-ages-2-4/magnific_bright-4k-commercial-prod_merubkrhjq.png", "/products/kids/toddler-sensory-explorer-hamper-ages-2-4/magnific_commercial-4k-ecommerce-p_vqx0c0aa47.png"],
    packagingItems: ['3 Jars Organic Non-Toxic Playdough', 'Chunky Palm-Grip Beeswax Crayons', 'Washable Finger Paints', 'Natural Wooden Stamp Rollers', 'Large-Print Animal Activity Pad', 'Play Mat Bag'],
    rating: 4.96,
    reviewCount: 174,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Screen-free sensory development champion for toddlers aged 2–4.',
  },
  {
    id: 'prod-kids-junior',
    name: 'Junior Creator Craft Kit (Ages 5–7)',
    subtitle: 'Air-Dry Clay with Tools, Dual-Tip Markers & Origami Paper Set',
    description: 'A guided hands-on craft kit featuring 12 vibrant colors of non-sticky air-dry modeling clay, child-safe sculpting tools, dual-tip sketch markers, an origami paper pack, and an illustrated activity book.',
    story: 'Inspires kindergarteners and early elementary school kids to build 3D figures, fold intricate animals, and express boundless creativity.',
    price: 999,
    originalPrice: 1200,
    category: 'kids-gifting',
    occasion: ['birthday', 'congratulations'],
    recipientTag: 'for-friends',
    budgetTier: '500-999',
    images: ["/products/kids/junior-creator-craft-hamper-ages-5-7/junior-creator-craft-hamper-ages-5-7.png", "/products/kids/junior-creator-craft-hamper-ages-5-7/magnific_minimalist-topdown-commer_wdmy6p9cxe.png", "/products/kids/junior-creator-craft-hamper-ages-5-7/magnific_studio-4k-commercial-prod_6amjjugijo.png", "/products/kids/junior-creator-craft-hamper-ages-5-7/magnific_studio-4k-commercial-prod_ljreexrgv9.png"],
    packagingItems: ['12 Colors Ultra-Light Air-Dry Clay', 'Safe Ergonomic Sculpting Tools', '12 Dual-Tip Sketch Markers', '50 Sheets Origami Paper', 'Step-by-Step Illustrated Activity Book'],
    rating: 4.93,
    reviewCount: 152,
    isBestSeller: true,
    isTrending: false,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 15,
    aiRecommendationReason: 'Develops fine motor precision and spatial creativity for ages 5 to 7.',
  },
  {
    id: 'prod-kids-artist',
    name: 'Young Artist Studio Hamper (Ages 8–11)',
    subtitle: 'Desktop Pine Easel + 2 Primed Canvases + 12 Acrylic Tubes & Brushes',
    description: 'A genuine desktop fine-art atelier. Includes a foldable natural pine wood tabletop easel, 2 primed stretched cotton canvas boards, 12 rich pigment acrylic paints, 6 professional nylon brushes, and a mixed-media sketchbook.',
    story: 'Transforms any child’s bedroom desk into an inspiring artist atelier. Gives aspiring young painters the autonomy to create frame-worthy canvas paintings.',
    price: 1299,
    originalPrice: 1600,
    category: 'kids-gifting',
    occasion: ['birthday', 'graduation'],
    recipientTag: 'for-friends',
    budgetTier: '1000-plus',
    images: ["/products/kids/young-artist-studio-hamper-ages-8-11/young-artist-studio-hamper-ages-8-11.png", "/products/kids/young-artist-studio-hamper-ages-8-11/magnific_highresolution-4k-b2c-pro_bxjo8o05y2.png"],
    packagingItems: ['Desktop Natural Pine Foldable Easel', '2 Stretched Cotton Canvas Boards (8x10)', '12 Vibrant Acrylic Paint Tubes', '6-Piece Nylon Brush Set with Palette', 'Heavyweight Mixed-Media Sketchpad'],
    rating: 4.97,
    reviewCount: 128,
    isBestSeller: false,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 20,
    aiRecommendationReason: 'Professional studio quality art setup empowering creative independence in ages 8–11.',
  },
  {
    id: 'prod-kids-maker',
    name: 'Master Maker DIY Hamper (Ages 12+)',
    subtitle: 'Punch-Needle Textile Kit + 24 Watercolor Pan + Cold-Press Block',
    description: 'A comprehensive creative maker kit combining modern fiber arts with classic watercolor. Features a punch-needle embroidery hoop and yarn set, 24 vibrant watercolor cake pans, 300GSM cold-press paper block, and water brush pens.',
    story: 'Designed for teenagers and curious creative minds. Helps teens master tactile fiber design and botanical illustration with rewarding, display-worthy results.',
    price: 1699,
    originalPrice: 2200,
    category: 'kids-gifting',
    occasion: ['birthday', 'graduation'],
    recipientTag: 'for-friends',
    budgetTier: '1000-plus',
    images: ["/products/kids/master-maker-diy-hamper-ages-12/master-maker-diy-hamper-ages-12.png", "/products/kids/master-maker-diy-hamper-ages-12/whatsapp-image-2026-09-14-at-5-10-10-pm-1.jpeg", "/products/kids/master-maker-diy-hamper-ages-12/whatsapp-image-2026-09-14-at-5-10-10-pm.jpeg", "/products/kids/master-maker-diy-hamper-ages-12/whatsapp-image-2026-09-14-at-5-10-11-pm-1.jpeg", "/products/kids/master-maker-diy-hamper-ages-12/whatsapp-image-2026-09-14-at-5-10-11-pm-2.jpeg", "/products/kids/master-maker-diy-hamper-ages-12/whatsapp-image-2026-09-14-at-5-10-11-pm.jpeg", "/products/kids/master-maker-diy-hamper-ages-12/magnific_luxury-4k-commercial-prod_1l4mh51r4r.png"],
    packagingItems: ['Punch-Needle Embroidery Kit with Wooden Hoop & Yarn', '24-Color Studio Watercolor Cake Pan', '300GSM Heavyweight Watercolor Block', '3 Refillable Water Reservoir Brushes', 'Magnetic Rigid Keepsake Storage Chest'],
    rating: 4.99,
    reviewCount: 110,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 25,
    aiRecommendationReason: 'Top-tier teenage mindfulness & hobby craft hamper with lasting decorative value.',
  },

  // 8. PREMIUM GIFTS: TIER BREAKDOWN (TASK1)
  {
    id: 'prod-prem-silver',
    name: 'Silver Reserve Luxury Dry Fruit & Truffle Box',
    subtitle: '2 Gourmet Glass Jars + European Truffles in Laser-Cut Sliding Box',
    description: 'An elegant wooden hamper containing two airtight hexagonal glass jars filled with whole California almonds and jumbo cashews, accompanied by an imported hazelnut truffle box in a laser-cut sliding lid wooden chest.',
    story: 'Tier 1 of our Royal Reserve collection. Tailored for corporate VIPs, festive team appreciation, and heartfelt family celebrations.',
    price: 2899,
    originalPrice: 3200,
    category: 'premium-gifts',
    occasion: ['anniversary', 'wedding', 'congratulations'],
    recipientTag: 'for-parents',
    budgetTier: '1000-plus',
    images: ["/products/premium/silver-reserve-hamper/whatsapp-image-2026-09-14-at-5-20-44-pm.jpeg", "/products/premium/silver-reserve-hamper/whatsapp-image-2026-09-14-at-5-20-45-pm.jpeg", "/products/premium/silver-reserve-hamper/magnific_commercial-4k-studio-prod_kspfjig16b.png", "/products/premium/silver-reserve-hamper/magnific_commercial-studio-product_mbc2hkydcm.png", "/products/premium/silver-reserve-hamper/magnific_silver-reserve-hamper-arr_xmqaolsbfo.png", "/products/premium/silver-reserve-hamper/magnific_silver-reserve-hamper-cap_3zewhv6rey.png"],
    packagingItems: ['Laser-Cut Sliding Lid Hardwood Chest', 'Hexagonal Glass Jar with California Almonds (200g)', 'Hexagonal Glass Jar with Jumbo Cashews (200g)', 'Imported Hazelnut Truffle Box (120g)', 'Embossed Gold Greeting Scroll'],
    rating: 4.94,
    reviewCount: 92,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: false,
    inStock: true,
    preparationTimeMinutes: 25,
    aiRecommendationReason: 'Elegant gourmet gift with high reusable value for wooden keepsake chest.',
  },
  {
    id: 'prod-prem-gold',
    name: 'Gold Executive Gourmet 4-Jar Hamper',
    subtitle: '4 Gourmet Nut Jars + Belgian Truffles + Honey in Laser-Engraved Box',
    description: 'A lavish custom hinged solid wood box enclosing four gourmet glass jars (California almonds, jumbo cashews, salted pistachios, dried cranberries), artisanal Belgian chocolate truffles, and a jar of single-origin wild forest honey with dipper.',
    story: 'Tier 2 of our Royal Reserve collection. Chosen by companies and families for key business partners, landmark anniversaries, and VIP milestones.',
    price: 3899,
    originalPrice: 4200,
    category: 'premium-gifts',
    occasion: ['anniversary', 'wedding', 'congratulations'],
    recipientTag: 'for-parents',
    budgetTier: '1000-plus',
    images: ["/products/premium/gold-executive-hamper/whatsapp-image-2026-09-14-at-5-12-55-pm-1.jpeg", "/products/premium/gold-executive-hamper/whatsapp-image-2026-09-14-at-5-12-55-pm.jpeg", "/products/premium/gold-executive-hamper/whatsapp-image-2026-09-14-at-5-12-56-pm-1.jpeg", "/products/premium/gold-executive-hamper/whatsapp-image-2026-09-14-at-5-12-56-pm-2.jpeg", "/products/premium/gold-executive-hamper/whatsapp-image-2026-09-14-at-5-12-56-pm.jpeg", "/products/premium/gold-executive-hamper/magnific_highend-commercial-produc_3zpwvkvrey.png", "/products/premium/gold-executive-hamper/magnific_luxury-45degree-angle-com_vqxpkwka47.png", "/products/premium/gold-executive-hamper/magnific_photograph-of-a-compact-g_sya9t3zub8.png", "/products/premium/gold-executive-hamper/magnific_photograph-of-a-gold-exec_fhs5oj5cdy.png", "/products/premium/gold-executive-hamper/magnific_photograph-of-a-luxury-go_lw3oy9cswo.png", "/products/premium/gold-executive-hamper/magnific_photograph-of-an-elongate_1l9uaybr4r.png"],
    packagingItems: ['Custom Laser-Engraved Hinged Hardwood Box', '4 Gourmet Glass Jars (Almonds, Cashews, Pistachios, Cranberries)', 'Artisanal Belgian Truffles Box', 'Single-Origin Raw Forest Honey with Wooden Dipper', 'Gold Ribbon & Satin Interior Bed'],
    rating: 4.98,
    reviewCount: 134,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 30,
    aiRecommendationReason: 'Premier gourmet selection with luxury laser-engraved wooden packaging.',
  },
  {
    id: 'prod-prem-imperial',
    name: 'Imperial Heritage Brass-Fitted Royal Chest',
    subtitle: '4 Luxury Nut Jars + Swiss Pralines + Kashmiri Kahwa + Scented Candle',
    description: 'Bloomora’s flagship heirloom experience. A dual-layer brass-fitted solid wood chest adorned with an engraved personalized nameplate. Houses 4 luxury nut jars, Swiss pralines, exotic Kashmiri Kahwa tea tin, and a hand-poured amber glass soy candle.',
    story: 'Reserved for CXOs, Board of Directors, royal wedding invitations, and once-in-a-lifetime family celebrations. An unforgettable statement of honor and luxury.',
    price: 4899,
    originalPrice: 5000,
    category: 'premium-gifts',
    occasion: ['anniversary', 'wedding', 'congratulations'],
    recipientTag: 'for-parents',
    budgetTier: '1000-plus',
    images: ["/products/premium/imperial-heritage-hamper/whatsapp-image-2026-09-14-at-5-16-43-pm-1.jpeg", "/products/premium/imperial-heritage-hamper/whatsapp-image-2026-09-14-at-5-16-43-pm.jpeg", "/products/premium/imperial-heritage-hamper/whatsapp-image-2026-09-14-at-5-16-44-pm-1.jpeg", "/products/premium/imperial-heritage-hamper/whatsapp-image-2026-09-14-at-5-16-44-pm.jpeg", "/products/premium/imperial-heritage-hamper/magnific_frontfacing-studio-shot-o_kspfjej16b.png", "/products/premium/imperial-heritage-hamper/magnific_product-photography-of-an_klpgngwkqp.png", "/products/premium/imperial-heritage-hamper/magnific_product-photography-of-an_p302mme42c.png", "/products/premium/imperial-heritage-hamper/magnific_product-photography-of-an_fhs56wkcdy.png", "/products/premium/imperial-heritage-hamper/magnific_toptier-luxury-corporate-_sy2537lub8.png"],
    packagingItems: ['Handcrafted Dual-Layer Brass-Fitted Wooden Chest', 'Custom Engraved Brass Monogram Nameplate', '4 Luxury Nut Jars (Mamra Almonds, W240 Cashews, Iranian Pistachios, Figs)', 'Luxury Swiss Praline Assortment', 'Artisanal Kashmiri Kahwa Exotic Tea Tin', 'Hand-Poured Amber Glass Scented Candle', 'Velvet Interior Lining'],
    rating: 5.0,
    reviewCount: 89,
    isBestSeller: true,
    isTrending: true,
    isSeasonal: false,
    isFeatured: true,
    inStock: true,
    preparationTimeMinutes: 40,
    aiRecommendationReason: 'India\'s most prestigious luxury gift chest with heirloom brass craftsmanship.',
  },
];

export const PARTNER_SHOPS: PartnerShop[] = [
  {
    id: 'shop-surampalem-1',
    name: 'Bloomora Express — Surampalem Hub',
    type: 'Gift Store',
    city: 'Surampalem',
    area: 'Aditya Campus Road',
    address: 'Shop #4, Main Gate Avenue, Near Aditya Engineering College',
    landmark: 'Opposite Student Food Court',
    rating: 4.9,
    distanceKm: 0.8,
    openHours: '8:00 AM - 10:00 PM',
    phone: '+91 98765 43210',
    image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=800&q=80',
    availableLockers: 6,
    isStoreOpen: true,
    deliveryZones: ['Aditya Campus', 'Surampalem Main Road', 'Peddapuram Road'],
  },
  {
    id: 'shop-rajahmundry-1',
    name: 'Royal Rose & Bakers Studio',
    type: 'Bakery',
    city: 'Rajahmundry',
    area: 'Danavaipeta',
    address: 'Door No. 12-4-8, Danavaipeta Main Road',
    landmark: 'Near SKVT College Ground',
    rating: 4.95,
    distanceKm: 1.4,
    openHours: '7:30 AM - 10:30 PM',
    phone: '+91 98765 12345',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    availableLockers: 8,
    isStoreOpen: true,
    deliveryZones: ['Danavaipeta', 'VL Puram', 'Devi Chowk', 'Railway Station Area'],
  },
  {
    id: 'shop-rajahmundry-2',
    name: 'Gowthami Flower Boutique',
    type: 'Flower Shop',
    city: 'Rajahmundry',
    area: 'VL Puram',
    address: 'Plot 45, Beside Devi Chowk Complex',
    landmark: 'Opposite State Bank Colony',
    rating: 4.88,
    distanceKm: 2.1,
    openHours: '6:30 AM - 9:30 PM',
    phone: '+91 98765 67890',
    image: 'https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=800&q=80',
    availableLockers: 4,
    isStoreOpen: true,
    deliveryZones: ['VL Puram', 'Kambala Cheruvu', 'Godavari Bund'],
  },
  {
    id: 'shop-vijayawada-1',
    name: 'Benz Circle Luxe Gifts & Cafe',
    type: 'Cafe',
    city: 'Vijayawada',
    area: 'Benz Circle',
    address: '40-1-12, MG Road, Benz Circle',
    landmark: 'Near Trendset Mall',
    rating: 4.92,
    distanceKm: 0.5,
    openHours: '8:00 AM - 11:00 PM',
    phone: '+91 98765 99887',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    availableLockers: 12,
    isStoreOpen: true,
    deliveryZones: ['Benz Circle', 'MG Road', 'Labbipet'],
  },
];
